-- Espelho da query principal dos saques (card Metabase 7973).
-- Fonte canônica: zig_risk_monitor/backend/sql/metabase_withdraw_query.sql
-- Filtro de data no WHERE: PAYMENTDATE (data de pagamento).

-- Query Metabase - Saques (card 7973)
-- ID_PLACE = código (UUID/números e letras). NOME_PLACE = nome por extenso do place.
-- Filtros opcionais: [[AND {{PLACE_NAME}}]] [[AND {{organizacao}}]] [[AND {{uf}}]] [[AND {{data}}]]
--
-- IMPORTANTE: alterações neste arquivo NÃO atualizam o Metabase automaticamente.
-- Copie o SQL completo para a pergunta/card no Metabase (ex. card 7973) e salve lá.

SELECT
   RFD.RFD_WITHDRAW_REQUESTS.ID AS ID_Saque,
   RFD.RFD_PLACES.ID AS ID_PLACE,
   DATEADD(HOUR, -3, RFD.RFD_WITHDRAW_REQUESTS.REQUESTDATE) AS Data_Solicitacao,
   DATEADD(HOUR, -3, RFD.RFD_WITHDRAW_REQUESTS.PAYMENTDATE) AS Data_Pagamento,
   RFD.RFD_PLACES.NAME AS NOME_PLACE,
   metabase.Clientes.doc_contrato AS CNPJ,
   RFD.RFD_ORGANIZATIONS.NAME AS NOME_ORGANIZACAO,
   RFD.RFD_ORGANIZATIONS.USERNAME AS ID_ORGANIZACAO,
   RFD.RFD_ZIG_LOCATIONS.NAME AS CIDADE,
   CASE
       WHEN TRIM(RFD.RFD_PAY_TRANSACTIONS.PAYMENTMETHOD) IS NULL
            OR TRIM(RFD.RFD_PAY_TRANSACTIONS.PAYMENTMETHOD) = ''
       THEN 'BOLETO'
       ELSE RFD.RFD_PAY_TRANSACTIONS.PAYMENTMETHOD
   END AS Metodo_Pagamento_Especifico,
   (RFD.RFD_WITHDRAW_REQUESTS.WITHDRAWVALUE / 100.0) AS Valor_Retirada,
   RFD.RFD_WITHDRAW_REQUESTS.STATUS,
   RFD.RFD_WITHDRAW_REQUESTS_PIX.RECEIVER,
   RFD.RFD_WITHDRAW_REQUESTS.CLIENTOBSERVATION AS Motivo,
   RFD.RFD_WITHDRAW_REQUESTS.BANKPAYMENTSLIPINFO AS Info_Boleto,
   RFD.RFD_BANK_ACCOUNTS.pixkey_type AS Tipo_Chave_PIX,
   RFD.RFD_BANK_ACCOUNTS.pixkey_value AS Valor_Chave_PIX,
   RFD.RFD_BANK_ACCOUNTS.RECEIVER_BANK AS Banco_Recebedor,
   RFD.RFD_BANK_ACCOUNTS.RECEIVER_AGENCY AS Agencia_Recebedor,
   CASE
       WHEN RFD.RFD_BANK_ACCOUNTS.RECEIVER_ACCOUNT IS NULL
       THEN PARSE_JSON(RFD.RFD_WITHDRAW_REQUESTS.BANKPAYMENTSLIPINFO):beneficiary::string
       ELSE RFD.RFD_BANK_ACCOUNTS.RECEIVER_ACCOUNT
   END AS Conta_Recebedor,
   CAST(COALESCE(RFD.RFD_ORGANIZATIONS.createdAt, RFD.RFD_PLACES.CREATEDAT) AS DATE) AS DATA_CRIACAO_PLACE_E_ORG
FROM RFD.RFD_WITHDRAW_REQUESTS
LEFT JOIN RFD.RFD_WITHDRAW_REQUESTS_PIX
    ON RFD.RFD_WITHDRAW_REQUESTS.ID = RFD.RFD_WITHDRAW_REQUESTS_PIX.WITHDRAWREQUESTID
LEFT JOIN RFD.RFD_PAY_TRANSACTIONS
    ON RFD.RFD_WITHDRAW_REQUESTS_PIX.ID = RFD.RFD_PAY_TRANSACTIONS.SYSTEMREFERENCE
LEFT JOIN RFD.RFD_BANK_ACCOUNTS
    ON RFD.RFD_WITHDRAW_REQUESTS.BANKACCOUNTID = RFD.RFD_BANK_ACCOUNTS.ID
LEFT JOIN RFD.RFD_PLACES
    ON RFD.RFD_WITHDRAW_REQUESTS.PLACEID = RFD.RFD_PLACES.ID
LEFT JOIN RFD.RFD_ORGANIZATIONS
    ON RFD.RFD_PLACES.ORGANIZATIONID = RFD.RFD_ORGANIZATIONS.ID
LEFT JOIN RFD.RFD_ZIG_LOCATIONS
    ON RFD.RFD_PLACES.ZIGLOCATIONID = RFD.RFD_ZIG_LOCATIONS.ID
LEFT JOIN metabase.Clientes
    ON RFD.RFD_WITHDRAW_REQUESTS.PLACEID = metabase.Clientes.fin_facts_place_id
WHERE 1=1
    AND RFD.RFD_WITHDRAW_REQUESTS.STATUS = 'Paid'
    AND RFD.RFD_WITHDRAW_REQUESTS.TYPE = 'Withdraw'
    AND DATE(RFD.RFD_WITHDRAW_REQUESTS.PAYMENTDATE) >= '2023-01-01'
    [[AND {{PLACE_NAME}}]]
    [[AND {{organizacao}}]]
    [[AND {{uf}}]]
    [[AND {{data}}]]
ORDER BY
    RFD.RFD_ORGANIZATIONS.NAME ASC,
    RFD.RFD_PLACES.NAME ASC;
